### ISSUE TITLE
Run stardist completely in colab

### ISSUE THREAD

**Issue by MDC91** [mpicbg-csbd/stardist#115]
Hey,

unfortunately, my laptop is not suitable for training the model. It would take a whole day.
My question is if I can run the whole example script by colab on a better PC and get a model I can export to Fiji?
We have one in our imaging facility, but I don't think that we are allowed to install a complete python environment and so on.

Marc

**Comment by uschmidt83** [comment]
Hi,

> My question is if I can run the whole example script by colab on a better PC and get a model I can export to Fiji?

Yes, basically.

We have an [example notebook that runs StarDist 2D on Colab](https://colab.research.google.com/github/mpicbg-csbd/stardist/blob/master/extras/stardist_example_2D_colab.ipynb). Otherwise, you can also try the StarDist notebooks provided by [ZeroCostDL4Mic](https://github.com/HenriquesLab/ZeroCostDL4Mic).

> We have one in our imaging facility, but I don't think that we are allowed to install a complete python environment and so on.

I would suggest to use your own computer if you're (starting to get) serious about using deep learning in your facility.

Best,
Uwe
