### ISSUE TITLE
malloc error: pointer being free was not allocated

### ISSUE THREAD

**Issue by lcferme** [mpicbg-csbd/stardist#41]
Hello everybody, 

I am a biologist - who enjoys learning about programming, so I know Python a little - and I would love to use StarDist-3D to segment some images of densely packed tissues that I am studying. I tried to import stardist to play around with it, but I immediately failed at the very first line of code and I do not know how to solve this issue. 
I imported tensorflow and stardist as indicated on your GitHub, together with GCC compiler. 
Though, when I run a .py file in the terminal, I cannot even import stardist that I get this error:

`Python(70696,0x109979dc0) malloc: *** error for object 0x144ef8d20: pointer being freed was not allocated 
Python(70696,0x109979dc0) malloc: *** set a breakpoint in malloc_error_break to debug`

So, my naive questions are:
Do you know what I am doing wrong and how I can solve it? 
Did anybody have the same issue?

I am using MacOS 10.15 and Python 3.7.3

I hope I will be able to use stardist soon!
Best, 

Lucrezia

**Comment by GFleishman** [comment]
If I may - I think this is your issue(?): https://github.com/mpicbg-csbd/stardist#macos
Basically Stardist is composed of both C++ and Python code. The C++ must be compiled. MacOS uses a default compiler for this which does not seem to work. The steps in that link describe how to get the correct compiler, specify it as what to use, and then rebuild and install Stardist. Note - the command it tells you to use, that should be run from within the Stardist source code directory (from where you cloned the repo).

**Comment by uschmidt83** [comment]
Hi Lucrezia,

thanks for trying StarDist and sorry for the late reply.
I don't know what the problem is in your case, maybe @maweigert has an idea.
(@GFleishman: I think installation would've failed if the default compiler (clang) was used.) 

To be honest, we don't really test StarDist much to be compatible with macOS because there is no GPU-support for TensorFlow, making it impractical to train a model (especially in 3D).
Hence, I strongly recommend to use a GPU-enabled Windows or Linux workstation if at all possible. If you just want to play with it for a while, using [Google Colab](https://colab.research.google.com) is probably worth a try.

Best,
Uwe

**Comment by lcferme** [comment]
Thanks everybody for the reply! Yep, it is my Mac (damn).
I followed step by step what was written in the troubleshooting part, also with the help of a friend who is a programmer and I still had this error. In the end, we found out that the error pops up when I run a .py file where I was importing Matplotlib and Stardist. I do not know why. Maybe there is a problem with multi threading.
Anyway, I can use stardist if I do not import matplotlib in the same file! But I will probably just install a virtual machine and use Linux. And thank you very much for the Colab link!

Best, 
Lucrezia
