### ISSUE TITLE
running notebook 1

### ISSUE THREAD

**Issue by anorak94** [mpicbg-csbd/stardist#52]
i am trying to run the first few cells from notebook 1 in the 2d examples folder. it works as expected on the data provided on the github page but there is no output when i try to run it on my data. im probably making some stupid mistake but i havent been able to figure it out. i make sure that my mask array is integer valued (i just have 0 and 1) dtype = "np.uint16" but the algorithm doestn give any output. i am attaching my data and notebook. 

https://we.tl/t-utCAjfFVNi

**Comment by uschmidt83** [comment]
Hi, thanks for trying the StarDist.

The problem is that your label image is a foreground/background segmentation mask, but StarDist needs an instance segmentation label image, where every object has its own id.

See the attached notebook for details: [stardist_spin_v1.html.zip](https://github.com/mpicbg-csbd/stardist/files/4574728/stardist_spin_v1.html.zip)

**Comment by anorak94** [comment]
thanks that worked

**Comment by anorak94** [comment]
just a small doubt i noticed that you normalised the training images should i do that while training the network. the images are 16 bit
