### ISSUE TITLE
Numpy is not in the requirements of setup.py

### ISSUE THREAD

**Issue by qjuppet** [mpicbg-csbd/stardist#71]
Hello,

I'm currently working to create an environment with Renku to train StarDist models and I had an issue regarding numpy that is not installed by default and is then installed at the same time as StarDist as both are in my requirements. As StarDist need numpy, its installation failed as numpy is not yet available. I fix my issue by installing numpy before my other requirements however I suggest to add numpy in the requirements of StarDist, I think it is missing.

**Comment by uschmidt83** [comment]
Hi, thanks for using StarDist.

> As StarDist need numpy, its installation failed as numpy is not yet available.

Yes, thanks for reminding me about that. Since `numpy` is typically installed, most people don't notice.

> I fix my issue by installing numpy before my other requirements

Yes, that's currently the only way.

> however I suggest to add numpy in the requirements of StarDist, I think it is missing.

It's not that simple. Actually, we implicitly require `numpy` through `csbdeep`.
The real issue is that we need `numpy` to even build the wheel (package), i.e. our `setup.py` imports from `numpy`.

I've [just added](https://github.com/mpicbg-csbd/stardist/commit/9bd7ff911bca5e87cbe70a8549b9c746d6d1c245) a `pyproject.toml`, which will hopefully fix this issue in the next release.

Best,
Uwe
