### ISSUE TITLE
Question about predict_instances_big for StarDist3D

### ISSUE THREAD

**Issue by Optimox** [mpicbg-csbd/stardist#87]
Hi,

First thank you and congratulations for this great work, this repo is truly amazing.

After reading the paper and training from scratch on my own data I have a blind spot that I'd like to fill.

### About my experiment

- I'm training on 10 big 3D grey stacks (~400x1000x1000) : 8 used for training, 2 for validation
- I have 5 new stacks that I'm using as test set to visually inspect the final results (will probably train with all later)
- Here is the training config I'm using (I have written some comments/questions for some parameters):
```
conf = Config3D (
    rays             = 48, # I have also tried 64 and 96
    grid             =  tuple(1 if a > 1.5 else 2 for a in anisotropy),
    anisotropy       = anisotropy, # equals to (1.1363636363636365, 1.0, 1.0)
    use_gpu          = True,
    n_channel_in     = n_channel, # 1 since I have grey scale images
    train_patch_size = (48,192,192), # should I make something more cubic?
    train_batch_size = 4, # Tried to set the largest batch size possible without get OOM error
    train_epochs = 50
)
```
- the training is fine everything is working like a charm
- Then I want to predict on my test set and here is what I'm doing:
```
n,h,w = X_test[2].shape
labels, details = model.predict_instances_big(X_test[2],
                                              axes='ZYX',
                                              block_size=(n, int(h/2), int(w/2)), #conf.train_patch_size
                                              min_overlap=16,
                                              context = (30,30,30), #(30,30,30),
                                              prob_thresh=0.4
                                             )
```
Everything works fine but I don't fully understand what's going on.

### Here are my questions:
1- block_size : I understand that we are treating the large volume with smaller blocks, but shouldn't block_size be the same as training size? If I set `block_size=conf.train_patch_size` I end up with issues with context and overlap, probably because I have one small dimension in training (48).
2-min_overlap : this is the overlap between blocks right? Why should it be larger than the size of a training object as written in the source code? I mean whatever the size here, I could have an object half in my block and half in the next one, so why is this so important?
3- context : I don't really understand the doc here `Amount of image context on all sides of a block, which is discarded.` What is the point of discarding some pixels on all sides? Are they discarded after the forward pass (for the NMS algorithm) or before (like a padding)?
4- `Also, it must hold that: min_overlap + 2*context < block_size.` I would easily understand that ` 2*context < block_size` in order not to discard everything, but why does `min_overlap` appears here? Would you have a link to a visual explanation how you define the different blocks? I think this could help me understand.
5- all my 3D stacks don't have the same sizes, should I change the above parameters according to each sizes or one set should work for all?
6- Overall would you have some advise to improve my pipeline? 

I hope you'll find some time to answer my questions, thank you for your time.

#### Side note

I'm working on a docker container of my own and installed the latest tensorflow version, I was getting this error when instantiating the StarDist3D`MemoryError: clEnqueueWriteBuffer failed: MEM_OBJECT_ALLOCATION_FAILURE` it was taking all my 12Go of GPU Memory (I have an RTX 2080 Ti).

Adding this lines of code solved my problem (just wanted to let you know in case someone has the same problem in the future):
```
# Deal with GPU growth : taken here https://www.tensorflow.org/guide/gpu
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)
```

**Comment by uschmidt83** [comment]
> First thank you and congratulations for this great work, this repo is truly amazing.

Thanks, I'm glad you like it!

> ```
> conf = Config3D (
>     ...
>     train_patch_size = (48,192,192), # should I make something more cubic?
>     train_batch_size = 4, # Tried to set the largest batch size possible without get OOM error
>     train_epochs = 50
> )
> ```

Since your object sizes are almost isotropic, you could try to use `(160,192,192)` or similar and decrease the batch size if needed, but I doubt it'll make much of a difference. Of course, if the objects are (often) larger than 48 pixels, it can make a big difference to enlarge the patch size such that objects are fully included.
The number of epochs seems a bit small, but you seem to know what you're doing.
 
> ```
> n,h,w = X_test[2].shape
> labels, details = model.predict_instances_big(X_test[2],
>                                               axes='ZYX',
>                                               block_size=(n, int(h/2), int(w/2)), #conf.train_patch_size
>                                               min_overlap=16,
>                                               context = (30,30,30), #(30,30,30),
>                                               prob_thresh=0.4
>                                              )
> ```

How big are the test stacks, i.e. what is `X_test[2].shape`?
If it has similar size than the training stacks, you can simply use `model.predict_instances`, which doesn't require you to set this many parameters. The only important one would be `n_tiles`, which determines into how many tiles the input stack will be chopped before prediction runs on the GPU. Please try using this function first.

The function `model.predict_instances_big` is only intended for *really* big images, which can't even be loaded in RAM or which require excessive computation and RAM requirements during the CPU-based non-maximum suppression step (to prune redundant object predictions) that runs after the CNN prediction on the GPU.

> 1- block_size : I understand that we are treating the large volume with smaller blocks, but shouldn't block_size be the same as training size? If I set `block_size=conf.train_patch_size` I end up with issues with context and overlap, probably because I have one small dimension in training (48).

No, `block_size` should be much larger in comparison to `min_overlap` and `context`. It's a bit difficult to explain in words and I should really make a diagram to explain what's happening under the hood. When calling `model.predict_instances`, the block size is essentially the entire input image.

> 2-min_overlap : this is the overlap between blocks right? Why should it be larger than the size of a training object as written in the source code? I mean whatever the size here, I could have an object half in my block and half in the next one, so why is this so important?

The main assumption is that each predicted object is fully contained in at least one of the blocks. This is not important for the CNN prediction, but the non-maximum suppression step.

> 3- context : I don't really understand the doc here `Amount of image context on all sides of a block, which is discarded.` What is the point of discarding some pixels on all sides? Are they discarded after the forward pass (for the NMS algorithm) or before (like a padding)?

No, this is just because the CNN prediction is less accurate at the image boundary. It is discarded after the NMS step.

> 4- `Also, it must hold that: min_overlap + 2*context < block_size.` I would easily understand that ` 2*context < block_size` in order not to discard everything, but why does `min_overlap` appears here? Would you have a link to a visual explanation how you define the different blocks? I think this could help me understand.

After the context is discarded on all sides, blocks still have to overlap at least `min_overlap` pixels. As you say, a diagram would make this clear. Note that the `model.predict_instances_big` is relatively new and really meant for people who have huge images. It's not a mainstream function.

> 5- all my 3D stacks don't have the same sizes, should I change the above parameters according to each sizes or one set should work for all?

The parameters can be the the same and really only depend on the CNN architecture (context) and the object sizes (min_overlap). However, the stack must obviously be bigger than the block size.

> 6- Overall would you have some advise to improve my pipeline?

Like I said, try using `model.predict_instances` instead and save yourself the headache ;)

> I'm working on a docker container of my own and installed the latest tensorflow version, I was getting this error when instantiating the StarDist3D`MemoryError: clEnqueueWriteBuffer failed: MEM_OBJECT_ALLOCATION_FAILURE` it was taking all my 12Go of GPU Memory (I have an RTX 2080 Ti).

Yes, TensorFlow unfortunately grabs all the GPU memory by default. That's why [our training notebook](https://nbviewer.jupyter.org/github/mpicbg-csbd/stardist/blob/master/examples/3D/2_training.ipynb) calls `limit_gpu_memory` to reserve 20% of the GPU memory to be used for OpenCL. Note that 20% may not be enough, it really depends on the patch size and the amount of total GPU memory.

> Adding this lines of code solved my problem (just wanted to let you know in case someone has the same problem in the future):

Allowing GPU memory growth is an alternative, but might be less efficient (not sure). As far as I recall, `limit_gpu_memory` also allows you to enable memory growth.

Best,
Uwe

**Comment by Optimox** [comment]
Thank you very much for the detailed answer, it helps me a lot.

All right, I'm going to:
- switch to `model.predict_instances` as my test stacks are of similar sizes as my training stacks (~400x1000x1000)
- play with `n_tiles` : should I just set this as low as possible as long as it fits in my GPU or should I do something smarter?
- try to make bigger train_patch_size : I'm a bit uncomfortable setting batch_size lower than 4 (or even 8) to be honest, do you perform gradient accumulation under the hood? Maybe I'm just freaking out for nothing but don't you feel that a batch_size of 2 is a bit too small to get a nice gradient descent?

Also I wanted to ask you about something else. 
At the moment I don't have nice labels that have been curated by humans (I might find some time to do this but later), but I have good enough binary masks that allows me to train algorithms like 3DUnets.
My problem is that some cells are close to each other, so my initial labels are not very good at differientiating adjacent cells (which creates big objects that don't look like cells at all) and same goes with the resulting UNet segmentation, that's why I decided to switch to StarDist3D.
First results from StarDist seem already much better at creating nice round cells, but in order to train StarDist I simply separated my binary mask using connex component : so my ground truth for StarDist never really shows adjacent cells (as they are merged into one same label).
Because of this I don't really trust the automated nms_thresh search function (labels are wrong so it's going to be hard for the search). So I played a bit with the nms_thresh to visually inspect the results but I'd like to understand better what 0.4 or 0.05 means for example. Does 0.4 means that I would tolerate that 40% of the volume of two cells (or a proxy of the volume) are actually overlapping? In terms of physics and biology, I don't expect my cells to be able to overlap at all, they can touch each other but that's it. Does this physics rule mean that setting nms_thresh to 0 makes sense? Or does the nms_thresh represents something completely different? ( I tried to have a look at the source code but I can't read C++!)

Hope my questions make sense.

Thanks again for your help,

Best,
Seb

**Comment by uschmidt83** [comment]
> * play with `n_tiles` : should I just set this as low as possible as long as it fits in my GPU or should I do something smarter?

Yes, essentially.

> * try to make bigger train_patch_size : I'm a bit uncomfortable setting batch_size lower than 4 (or even 8) to be honest, do you perform gradient accumulation under the hood? Maybe I'm just freaking out for nothing but don't you feel that a batch_size of 2 is a bit too small to get a nice gradient descent?

Keep in mind that every pixel (that belongs to an object) contributes a gradient signal. We often trained with a batch size of 1 and didn't see a problem.

> My problem is that some cells are close to each other, so my initial labels are not very good at differientiating adjacent cells (which creates big objects that don't look like cells at all) and same goes with the resulting UNet segmentation, that's why I decided to switch to StarDist3D.
> First results from StarDist seem already much better at creating nice round cells, but in order to train StarDist I simply separated my binary mask using connex component : so my ground truth for StarDist never really shows adjacent cells (as they are merged into one same label).

I don't see how you can overcome this problem without fixing the ground truth (at least in part). What we have seen is that StarDist can potentially be trained with labelling errors – as long as these are not biased, which they seem to be in your case (i.e. touching nuclei are always incorrectly merged).

> Because of this I don't really trust the automated nms_thresh search function (labels are wrong so it's going to be hard for the search).

(As I said above, I wouldn't trust the results in general.)
Note that the automatic threshold finding is in some sense just for convenience to set good thresholds that work well on average. Depending on the application, one would, e.g., increase the probability threshold to prefer more accurate predictions (fewer false positives) at the expense of missing some nuclei (more false negatives).

> Does 0.4 means that I would tolerate that 40% of the volume of two cells (or a proxy of the volume) are actually overlapping?

Yes.

> In terms of physics and biology, I don't expect my cells to be able to overlap at all, they can touch each other but that's it. Does this physics rule mean that setting nms_thresh to 0 makes sense?

Yes, in some sense. But keep in mind that predicted nucleus shapes are not perfect and thus can overlap to some degree. That's why you typically want to allow for some overlap.

Best,
Uwe

**Comment by Optimox** [comment]
Thank you very much for your detailed answer and your time.

Keep up the great work!

Best,
Seb
