### ISSUE TITLE
Training is slower with larger batch size

### ISSUE THREAD

**Issue by Optimox** [mpicbg-csbd/stardist#94]
Hi,

I noticed something a bit surprising.

With all other parameters equal, switching from batch size of 1 to 2 will make the training time for one epoch go from 33s to 45s.
I would expect to get a memory error if my GPU can't handle bigger batches but everything runs ok but slower.

I also always get this warning at the beginning of training :
```
WARNING:tensorflow | Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0825s vs `on_train_batch_end` time: 0.2270s). Check your callbacks.
```
So I was thinking that maybe the loss computation for validation does not scale very well and that the training time might no be the problem.

Any hint on how to improve on this? (I'm using StarDist3D)

Thanks for your help!

**Comment by uschmidt83** [comment]
> With all other parameters equal, switching from batch size of 1 to 2 will make the training time for one epoch go from 33s to 45s.
> I would expect to get a memory error if my GPU can't handle bigger batches but everything runs ok but slower.
> ...
> Any hint on how to improve on this? (I'm using StarDist3D)

I assume this is due to a CPU bottleneck, not a GPU one. During training, our data generator converts the annotated label images to the format (radial distances) needed for training the model. This can be somewhat compute intensive, especially in 3D. This computation happens on the CPU, unless `gputools` is installed and `use_gpu = True` in the config (cf. cell 10 of the [training notebook](https://nbviewer.jupyter.org/github/mpicbg-csbd/stardist/blob/master/examples/3D/2_training.ipynb)). If you do that, training should run faster, especially if you don't have a powerful CPU (with many cores).


> I also always get this warning at the beginning of training :
> 
> ```
> WARNING:tensorflow | Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0825s vs `on_train_batch_end` time: 0.2270s). Check your callbacks.
> ```
> 
> So I was thinking that maybe the loss computation for validation does not scale very well and that the training time might no be the problem.
> 

I think that's a red herring and unrelated.

Best,
Uwe

**Comment by Optimox** [comment]
I do have a powerful CPU and `gpu_tools` is installed and I set `use_gpu = True`. It's no big deal anyway, thanks!
